services:
  - type: web
    name: golden-anemia-demo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/web_app_mock.py
    envVars:
      - key: PORT
        value: 10000
